In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
%matplotlib inline

In [4]:
train = pd.read_csv('train.csv')

In [5]:
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [6]:
test = pd.read_csv('test.csv')

In [7]:
test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

# Feature Scaling and Mean Normalization

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()

In [11]:
scaler.fit(train.drop('label', axis=1))

/home/harsh/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [12]:
scaled_features = scaler.transform(train.drop('label', axis=1))

/home/harsh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


In [13]:
scaled_test_features = scaler.transform(test)

/home/harsh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


In [14]:
scaled_features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
df_feat = pd.DataFrame(scaled_features, columns=train.columns[1:])

In [16]:
df_feat_test = pd.DataFrame(scaled_test_features, columns=test.columns)

In [17]:
df_feat.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0     0.0  ... -0.034737  -0.02527 -0.018026 -0.011473 -0.009099 -0.006897   
1     0.0  ... -0.034737  -0.02527 -0.018026 -0.011473 -0.009099 -0.006897   
2     0.0  ... -0.034737  -0.02527 -0.018026 -0.011473 -0.009099 -0.006897   
3     0.0  ... -0.034737  -0.02527 -0.018026 -0.011473 -0.009099 -0.006897   
4     0.0  ... -0.034737  -0.02527 -0.018026 -0.011473 -0.009099 -0.006897   

   pixel780  pixel781  pixel782  pixel783  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 784 columns]

In [18]:
df_feat_test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0     0.0  ... -0.034737  -0.02527 -0.018026 -0.011473 -0.009099 -0.006897   
1     0.0  ... -0.034737  -0.02527 -0.018026 -0.011473 -0.009099 -0.006897   
2     0.0  ... -0.034737  -0.02527 -0.018026 -0.011473 -0.009099 -0.006897   
3     0.0  ... -0.034737  -0.02527 -0.018026 -0.011473 -0.009099 -0.006897   
4     0.0  ... -0.034737  -0.02527 -0.018026 -0.011473 -0.009099 -0.006897   

   pixel780  pixel781  pixel782  pixel783  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 784 columns]

# Reducing Feature Size using PCA

In [19]:
from sklearn.decomposition import PCA

In [20]:
pca = PCA(n_components=100)

In [21]:
pca.fit(df_feat)

PCA(copy=True, iterated_power='auto', n_components=100, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [22]:
x_pca = pca.transform(df_feat)

In [23]:
x_pca.shape

(42000, 100)

In [24]:
df_feat.shape

(42000, 784)

# Splitting data into training and CV sets

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X = x_pca
y = train['label']

In [32]:
X_train, X_cv, y_train, y_cv = train_test_split(X, y, test_size=0.3)

# Random Forest Estimator

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [39]:
rfc = RandomForestClassifier(n_estimators=200)

In [40]:
rfc.fit(X=X_train, y=y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [41]:
preds = rfc.predict(X_cv)

In [42]:
from sklearn.metrics import classification_report, confusion_matrix

In [44]:
print(confusion_matrix(y_cv, preds))
print('\n')
print(classification_report(y_cv, preds))

[[1265    0    4    5    2    5   15    1    2    0]
 [   0 1393    9    5    1    1    5    1    7    0]
 [  13    3 1203   17    6    1    6   13   19    1]
 [   3    4   27 1170    0   14    2   21   31    4]
 [   2   10   13    1 1133    1    4    5    2   37]
 [  13    0    3   51    3 1009   16    4    9   11]
 [   7    1    3    1    2   17 1164    0    7    0]
 [   6    6   14    7    8    0    0 1226    0   30]
 [   7   11   17   38    6   30    3    4 1107   11]
 [   7    0    4   13   27    7    0   31   10 1162]]


              precision    recall  f1-score   support

           0       0.96      0.97      0.96      1299
           1       0.98      0.98      0.98      1422
           2       0.93      0.94      0.93      1282
           3       0.89      0.92      0.91      1276
           4       0.95      0.94      0.95      1208
           5       0.93      0.90      0.92      1119
           6       0.96      0.97      0.96      1202
           7       0.94      0.95 

# Variable Feature Size for PCA

In [53]:
feat_size = [100, 150, 200, 250, 300, 350, 400, 450, 500, 550]

for size in feat_size:
    pca = PCA(n_components=size)
    pca.fit(df_feat)
    x_pca = pca.transform(df_feat)
    X = x_pca
    y = train['label']
    X_train, X_cv, y_train, y_cv = train_test_split(X, y, test_size=0.3)
    rfc = RandomForestClassifier(n_estimators=100)
    rfc.fit(X=X_train, y=y_train)
    preds = rfc.predict(X_cv)
    print(classification_report(y_cv, preds))
    print('\n\n')

              precision    recall  f1-score   support

           0       0.96      0.97      0.97      1268
           1       0.98      0.98      0.98      1431
           2       0.93      0.94      0.93      1247
           3       0.90      0.91      0.91      1323
           4       0.93      0.94      0.93      1150
           5       0.93      0.90      0.92      1162
           6       0.96      0.96      0.96      1287
           7       0.93      0.94      0.93      1285
           8       0.92      0.90      0.91      1188
           9       0.91      0.90      0.91      1259

   micro avg       0.94      0.94      0.94     12600
   macro avg       0.93      0.93      0.93     12600
weighted avg       0.94      0.94      0.94     12600




              precision    recall  f1-score   support

           0       0.96      0.98      0.97      1250
           1       0.98      0.98      0.98      1370
           2       0.92      0.93      0.93      1240
           3       0.

In [55]:
feat_size = [10, 25, 50]

for size in feat_size:
    pca = PCA(n_components=size)
    pca.fit(df_feat)
    x_pca = pca.transform(df_feat)
    X = x_pca
    y = train['label']
    X_train, X_cv, y_train, y_cv = train_test_split(X, y, test_size=0.3)
    rfc = RandomForestClassifier(n_estimators=100)
    rfc.fit(X=X_train, y=y_train)
    preds = rfc.predict(X_cv)
    print(classification_report(y_cv, preds))
    print('\n\n')

              precision    recall  f1-score   support

           0       0.93      0.95      0.94      1257
           1       0.97      0.98      0.97      1381
           2       0.92      0.93      0.92      1211
           3       0.88      0.87      0.87      1285
           4       0.86      0.85      0.85      1195
           5       0.89      0.85      0.87      1169
           6       0.95      0.96      0.95      1278
           7       0.92      0.91      0.91      1310
           8       0.87      0.86      0.86      1263
           9       0.81      0.82      0.82      1251

   micro avg       0.90      0.90      0.90     12600
   macro avg       0.90      0.90      0.90     12600
weighted avg       0.90      0.90      0.90     12600




              precision    recall  f1-score   support

           0       0.96      0.97      0.97      1299
           1       0.98      0.97      0.98      1389
           2       0.93      0.95      0.94      1231
           3       0.

In [56]:
feat_size = [75]

for size in feat_size:
    pca = PCA(n_components=size)
    pca.fit(df_feat)
    x_pca = pca.transform(df_feat)
    X = x_pca
    y = train['label']
    X_train, X_cv, y_train, y_cv = train_test_split(X, y, test_size=0.3)
    rfc = RandomForestClassifier(n_estimators=100)
    rfc.fit(X=X_train, y=y_train)
    preds = rfc.predict(X_cv)
    print(classification_report(y_cv, preds))
    print('\n\n')

              precision    recall  f1-score   support

           0       0.96      0.98      0.97      1285
           1       0.99      0.98      0.98      1428
           2       0.92      0.93      0.93      1279
           3       0.90      0.92      0.91      1273
           4       0.94      0.95      0.94      1192
           5       0.93      0.92      0.92      1097
           6       0.95      0.96      0.96      1249
           7       0.94      0.95      0.95      1303
           8       0.93      0.89      0.91      1175
           9       0.92      0.90      0.91      1319

   micro avg       0.94      0.94      0.94     12600
   macro avg       0.94      0.94      0.94     12600
weighted avg       0.94      0.94      0.94     12600






# Variable number of estimators

In [57]:
pca = PCA(n_components=75)

In [58]:
pca.fit(df_feat)

PCA(copy=True, iterated_power='auto', n_components=75, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [59]:
x_pca = pca.transform(df_feat)

In [60]:
X = x_pca

In [61]:
y = train['label']

In [62]:
X_train, X_cv, y_train, y_cv = train_test_split(X, y, test_size=0.3)

In [63]:
estim = [100, 150, 200, 250, 300, 350, 400]

for est in estim:
    rfc = RandomForestClassifier(n_estimators=est)
    rfc.fit(X=X_train, y=y_train)
    preds = rfc.predict(X_cv)
    print(classification_report(y_cv, preds))
    print('\n\n')

              precision    recall  f1-score   support

           0       0.94      0.97      0.96      1203
           1       0.98      0.98      0.98      1385
           2       0.93      0.95      0.94      1279
           3       0.90      0.93      0.91      1295
           4       0.93      0.95      0.94      1223
           5       0.95      0.88      0.91      1160
           6       0.96      0.97      0.96      1295
           7       0.93      0.94      0.94      1291
           8       0.94      0.90      0.91      1201
           9       0.90      0.89      0.89      1268

   micro avg       0.94      0.94      0.94     12600
   macro avg       0.94      0.94      0.94     12600
weighted avg       0.94      0.94      0.94     12600




              precision    recall  f1-score   support

           0       0.95      0.97      0.96      1203
           1       0.98      0.98      0.98      1385
           2       0.92      0.95      0.93      1279
           3       0.

In [64]:
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X=X_train, y=y_train)
preds = rfc.predict(X_cv)
print(classification_report(y_cv, preds))
print('\n\n')

              precision    recall  f1-score   support

           0       0.94      0.97      0.96      1203
           1       0.98      0.98      0.98      1385
           2       0.92      0.95      0.93      1279
           3       0.90      0.93      0.92      1295
           4       0.93      0.94      0.94      1223
           5       0.95      0.89      0.92      1160
           6       0.96      0.96      0.96      1295
           7       0.94      0.94      0.94      1291
           8       0.94      0.90      0.92      1201
           9       0.89      0.89      0.89      1268

   micro avg       0.94      0.94      0.94     12600
   macro avg       0.94      0.93      0.93     12600
weighted avg       0.94      0.94      0.94     12600






In [65]:
x_pca_test = pca.transform(df_feat_test)

In [66]:
X_test = x_pca_test

In [68]:
test_preds = rfc.predict(X_test)

In [69]:
test_preds

array([2, 0, 9, ..., 3, 9, 2])

In [70]:
submit = pd.read_csv('sample_submission.csv', index_col=0)
submit.head()

Label
ImageId       
1            0
2            0
3            0
4            0
5            0

In [71]:
submit['Label'] = test_preds

In [72]:
submit.head()

Label
ImageId       
1            2
2            0
3            9
4            4
5            3

In [73]:
submit.to_csv('submission.csv')